spring:
  datasource:
    url: jdbc:mysql://47.110.130.104:3306/boot_unit?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: Li##199598

dubbo:
  application:
    name: unit-application-provider
  registry:
    id: zk-registry
    address: zookeeper://47.110.130.104:2181
  config-center:
    address: zookeeper://47.110.130.104:2181
  metadata-report:
    address: zookeeper://47.110.130.104:2181